spring:
  config:
    import: "optional:file:.env[.properties]"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      properties:
        format_sql: true
        show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      repositories:
        enabled: false

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}?currentSchema=public
    username: ${POSTGRES_NAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver



jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_TIME}
  expiration: ${JWT_EXPIRATION_TIME}